name: Create adaptation PR

on:
  pull_request_target:
    types: [labeled]
    branches: [master]
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  main:
    runs-on: ubuntu-slim
    environment: master

    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.DOWNSTREAM_APP_CLIENT_ID }}
          private-key: ${{ secrets.DOWNSTREAM_APP_PRIVATE_KEY }}

      # - uses: Garmelon/test-downstream/.downstream/actions/adaptation-pr@master
      - uses: leanprover/downstream/actions/adaptation-pr@actions
        with:
          app-token: ${{ steps.app-token.outputs.token }}
          app-slug: ${{ steps.app-token.outputs.app-slug }}
          downstream-repo: Garmelon/test-downstream
          downstream-workflow: adaptation-pr.yml
